# Generated by Django 3.1.2 on 2020-10-01 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TodoList',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('developer', models.CharField(max_length=255, verbose_name='Developer')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.CharField(max_length=32, verbose_name='Description')),
                ('time_worked', models.PositiveIntegerField(verbose_name='Time Worked')),
                ('estimated_time', models.FloatField(verbose_name='Estimated Time')),
                ('is_completed', models.BooleanField(default=True, verbose_name='Is Completed')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated')),
            ],
        ),
    ]
