# Generated by Django 3.1.2 on 2020-10-01 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TodoList',
            new_name='Task',
        ),
    ]
